"""
SQLAlchemy 2.x models for Multi-Agent execution, findings, and reasoning results.
Supports multiple agent runs per incident with full lineage.
"""

from datetime import datetime
from typing import TYPE_CHECKING, Any, Optional
from sqlalchemy import DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database.base import Base, TimestampMixin, generate_uuid_str

if TYPE_CHECKING:
    from backend.database.models.incident import Incident, IncidentEvidence
    from backend.database.models.remediation import RemediationPlan


class AgentRun(Base, TimestampMixin):
    """Execution record for an ADK specialist or supervisor agent."""
    __tablename__ = "agent_runs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid_str)
    incident_id: Mapped[str] = mapped_column(String(36), ForeignKey("incidents.id", ondelete="CASCADE"), index=True, nullable=False)
    agent_name: Mapped[str] = mapped_column(String(64), index=True, nullable=False)  # e.g., "RenderQAAgent"
    agent_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)  # SUPERVISOR, SPECIALIST, STRATEGY
    status: Mapped[str] = mapped_column(String(32), default="RUNNING", index=True, nullable=False)  # RUNNING, COMPLETED, FAILED
    iteration: Mapped[int] = mapped_column(Integer, default=1, index=True, nullable=False)  # Supports multiple runs per incident
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    prompt_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    input_context: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    output_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="agent_runs")
    findings: Mapped[list["AgentFinding"]] = relationship("AgentFinding", back_populates="agent_run", cascade="all, delete-orphan")
    reasoning_results: Mapped[list["ReasoningResult"]] = relationship("ReasoningResult", back_populates="agent_run")


class AgentFinding(Base, TimestampMixin):
    """Specific diagnostic, anomaly, or hypothesis emitted by an agent run."""
    __tablename__ = "agent_findings"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid_str)
    agent_run_id: Mapped[str] = mapped_column(String(36), ForeignKey("agent_runs.id", ondelete="CASCADE"), index=True, nullable=False)
    evidence_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("incident_evidence.id", ondelete="SET NULL"), index=True, nullable=True)
    finding_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)  # SHADER_CRASH, GPU_OOM, BROKEN_USD_REF
    severity: Mapped[str] = mapped_column(String(32), default="MEDIUM", index=True, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)  # 0.0 - 1.0
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    structured_payload: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)

    # Relationships
    agent_run: Mapped["AgentRun"] = relationship("AgentRun", back_populates="findings")
    evidence: Mapped[Optional["IncidentEvidence"]] = relationship("IncidentEvidence", back_populates="findings")


class ReasoningResult(Base, TimestampMixin):
    """Synthesized root-cause analysis generated by the Reasoning Engine / Supervisor."""
    __tablename__ = "reasoning_results"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid_str)
    incident_id: Mapped[str] = mapped_column(String(36), ForeignKey("incidents.id", ondelete="CASCADE"), index=True, nullable=False)
    agent_run_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("agent_runs.id", ondelete="SET NULL"), index=True, nullable=True)
    root_cause: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=1.0, index=True, nullable=False)  # 0.0 - 1.0
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    hypotheses_evaluated: Mapped[list[dict[str, Any]]] = mapped_column(JSON, default=list)
    evidence_refs: Mapped[list[str]] = mapped_column(JSON, default=list)  # List of referenced evidence UUIDs

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="reasoning_results")
    agent_run: Mapped[Optional["AgentRun"]] = relationship("AgentRun", back_populates="reasoning_results")
    remediation_plans: Mapped[list["RemediationPlan"]] = relationship("RemediationPlan", back_populates="reasoning_result")
