"""initial_vfx_schema

Revision ID: 86ed12b12471
Revises: 
Create Date: 2026-09-08 22:32:02.799732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ed12b12471'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('render_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('gpu_model', sa.String(length=128), nullable=True),
    sa.Column('gpu_memory_gb', sa.Float(), nullable=True),
    sa.Column('cpu_model', sa.String(length=128), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_nodes_health_score'), 'render_nodes', ['health_score'], unique=False)
    op.create_index(op.f('ix_render_nodes_node_id'), 'render_nodes', ['node_id'], unique=True)
    op.create_index(op.f('ix_render_nodes_status'), 'render_nodes', ['status'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_code'), 'sequences', ['code'], unique=False)
    op.create_index(op.f('ix_sequences_project_id'), 'sequences', ['project_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('frame_start', sa.Integer(), nullable=True),
    sa.Column('frame_end', sa.Integer(), nullable=True),
    sa.Column('assigned_lead', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_code'), 'shots', ['code'], unique=False)
    op.create_index(op.f('ix_shots_project_id'), 'shots', ['project_id'], unique=False)
    op.create_index(op.f('ix_shots_sequence_id'), 'shots', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_shots_status'), 'shots', ['status'], unique=False)
    op.create_table('render_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('shot_id', sa.String(length=36), nullable=True),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('renderer', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('frame_range', sa.String(length=64), nullable=True),
    sa.Column('submitted_by', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['render_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_jobs_job_id'), 'render_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_render_jobs_node_id'), 'render_jobs', ['node_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_project_id'), 'render_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_shot_id'), 'render_jobs', ['shot_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_status'), 'render_jobs', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('shot_id', sa.String(length=36), nullable=True),
    sa.Column('render_job_id', sa.String(length=36), nullable=True),
    sa.Column('render_node_id', sa.String(length=36), nullable=True),
    sa.Column('error_signature', sa.String(length=256), nullable=True),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_node_id'], ['render_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_correlation_id'), 'incidents', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_incidents_error_signature'), 'incidents', ['error_signature'], unique=False)
    op.create_index(op.f('ix_incidents_event_type'), 'incidents', ['event_type'], unique=False)
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_render_job_id'), 'incidents', ['render_job_id'], unique=False)
    op.create_index(op.f('ix_incidents_render_node_id'), 'incidents', ['render_node_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_shot_id'), 'incidents', ['shot_id'], unique=False)
    op.create_index(op.f('ix_incidents_source_system'), 'incidents', ['source_system'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_incident_id'), 'agent_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_iteration'), 'agent_runs', ['iteration'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_evidence_type'), 'incident_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_table('agent_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('finding_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['incident_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_agent_run_id'), 'agent_findings', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_evidence_id'), 'agent_findings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_finding_type'), 'agent_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_agent_findings_severity'), 'agent_findings', ['severity'], unique=False)
    op.create_table('reasoning_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hypotheses_evaluated', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_results_agent_run_id'), 'reasoning_results', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_reasoning_results_confidence'), 'reasoning_results', ['confidence'], unique=False)
    op.create_index(op.f('ix_reasoning_results_incident_id'), 'reasoning_results', ['incident_id'], unique=False)
    op.create_table('remediation_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('reasoning_result_id', sa.String(length=36), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('rollback_strategy', sa.Text(), nullable=True),
    sa.Column('preventive_measures', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reasoning_result_id'], ['reasoning_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_plans_incident_id'), 'remediation_plans', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_reasoning_result_id'), 'remediation_plans', ['reasoning_result_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_risk_level'), 'remediation_plans', ['risk_level'], unique=False)
    op.create_index(op.f('ix_remediation_plans_status'), 'remediation_plans', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_plan_id'), 'actions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('policy_evaluated', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_plan_id'), 'approval_requests', ['plan_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_plan_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_plan_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_remediation_plans_status'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_risk_level'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_reasoning_result_id'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_incident_id'), table_name='remediation_plans')
    op.drop_table('remediation_plans')
    op.drop_index(op.f('ix_reasoning_results_incident_id'), table_name='reasoning_results')
    op.drop_index(op.f('ix_reasoning_results_confidence'), table_name='reasoning_results')
    op.drop_index(op.f('ix_reasoning_results_agent_run_id'), table_name='reasoning_results')
    op.drop_table('reasoning_results')
    op.drop_index(op.f('ix_agent_findings_severity'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_finding_type'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_evidence_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent_run_id'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_evidence_type'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_iteration'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_incident_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_system'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_shot_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_render_node_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_render_job_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_event_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_error_signature'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_correlation_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_render_jobs_status'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_shot_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_project_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_node_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_job_id'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_shots_status'), table_name='shots')
    op.drop_index(op.f('ix_shots_sequence_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_project_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_code'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_sequences_project_id'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_code'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_render_nodes_status'), table_name='render_nodes')
    op.drop_index(op.f('ix_render_nodes_node_id'), table_name='render_nodes')
    op.drop_index(op.f('ix_render_nodes_health_score'), table_name='render_nodes')
    op.drop_table('render_nodes')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
