"""
VFX Incident Platform Database and Persistence Subsystem.
"""

from backend.database.base import Base
from backend.database.models import (
    Action,
    AgentFinding,
    AgentRun,
    AuditLog,
    Incident,
    IncidentEvidence,
    Project,
    ReasoningResult,
    RemediationPlan,
    RenderJob,
    RenderNode,
    Sequence,
    Shot,
    ApprovalRequest,
)
from backend.database.repositories import (
    ActionRepository,
    AgentFindingRepository,
    AgentRunRepository,
    ApprovalRequestRepository,
    AuditLogRepository,
    BaseRepository,
    IncidentEvidenceRepository,
    IncidentRepository,
    ProjectRepository,
    ReasoningResultRepository,
    RemediationPlanRepository,
    RenderJobRepository,
    RenderNodeRepository,
    SequenceRepository,
    ShotRepository,
)
from backend.database.services import TraceabilityService
from backend.database.session import (
    SessionLocal,
    drop_db,
    engine,
    get_database_url,
    get_db,
    init_db,
)

__all__ = [
    "Base",
    "init_db",
    "drop_db",
    "get_db",
    "engine",
    "SessionLocal",
    "get_database_url",
    "Project",
    "Sequence",
    "Shot",
    "RenderJob",
    "RenderNode",
    "Incident",
    "IncidentEvidence",
    "AgentRun",
    "AgentFinding",
    "ReasoningResult",
    "RemediationPlan",
    "ApprovalRequest",
    "Action",
    "AuditLog",
    "BaseRepository",
    "ProjectRepository",
    "SequenceRepository",
    "ShotRepository",
    "RenderNodeRepository",
    "RenderJobRepository",
    "IncidentRepository",
    "IncidentEvidenceRepository",
    "AgentRunRepository",
    "AgentFindingRepository",
    "ReasoningResultRepository",
    "RemediationPlanRepository",
    "ApprovalRequestRepository",
    "ActionRepository",
    "AuditLogRepository",
    "TraceabilityService",
]
