import { ClusterNodeHealth, IncidentSummary } from "./types";

export const MOCK_INCIDENTS: IncidentSummary[] = [
  {
    id: "inc-1042-oom",
    correlation_id: "corr-arnold-gpu-01",
    title: "Arnold GPU Out of Memory on Frame 1042 (80GB Pool Recommended)",
    description: "Render job failed with CUDA error 2: out of memory during volume texture decompression on hero hero_creature asset.",
    severity: "HIGH",
    status: "AWAITING_APPROVAL",
    event_type: "RENDER_JOB_FAILED",
    source_system: "deadline",
    project: "DUNE_PART_3",
    sequence: "SQ040",
    shot: "SH0120",
    job_id: "job-arnold-8821",
    node_id: "node-blade-42",
    error_signature: "CUDA_OUT_OF_MEMORY:80GB_RECOMMENDED",
    created_at: "2026-09-08T17:35:00Z",
    updated_at: "2026-09-08T17:42:00Z",
    evidence: [
      {
        id: "ev-01",
        evidence_type: "NODE_TELEMETRY",
        source: "deadline",
        title: "Node blade-42 GPU Telemetry",
        structured_data: {
          gpu_model: "NVIDIA RTX A6000 (48GB)",
          gpu_memory_used: "47.8 GB / 48.0 GB",
          gpu_utilization: 99.8,
          temperature: "84.2 C",
          pcie_retransmits: 0,
        },
        raw_content: "2026-09-08 17:34:58 [ERROR] [gpu] CUDA error 2 (out of memory) allocating 1420MB buffer for volume shadow map.",
        captured_at: "2026-09-08T17:35:01Z",
      },
      {
        id: "ev-02",
        evidence_type: "RENDER_LOG",
        source: "deadline",
        title: "Arnold Render Log Excerpt",
        structured_data: {
          renderer: "Arnold 7.3.1.0",
          failed_frame: 1042,
          allocated_peak_mb: 48920,
          vdb_grids: ["density", "temperature", "flame"],
        },
        raw_content: "00:04:12 48920MB ERROR | [gpu] failed to allocate device memory for grid 'density.vdb' at level 0",
        captured_at: "2026-09-08T17:35:02Z",
      },
      {
        id: "ev-03",
        evidence_type: "USD_DEPENDENCY",
        source: "asset_storage",
        title: "USD Stage Texture & Volume Payload Map",
        structured_data: {
          root_layer: "/jobs/DUNE_PART_3/SQ040/SH0120/fx/creature_fire_v004.usd",
          uncompressed_vdb_size_gb: 34.2,
          texture_count: 84,
          missing_files: 0,
        },
        raw_content: "Resolved 84 texture dependencies. Volume /World/FX/fire_cache references uncompressed 34.2GB VDB buffer.",
        captured_at: "2026-09-08T17:35:10Z",
      },
    ],
    agent_runs: [
      {
        id: "run-sup-01",
        agent_name: "ADK Supervisor Agent",
        agent_type: "SUPERVISOR",
        status: "COMPLETED",
        started_at: "2026-09-08T17:35:15Z",
        completed_at: "2026-09-08T17:35:20Z",
        output_summary: "Triaged incident as render farm failure with suspected memory bottleneck. Delegated investigation to Render QA, Hardware, Asset Validation, and Historical specialists.",
        findings: [],
      },
      {
        id: "run-qa-01",
        agent_name: "Render QA Specialist",
        agent_type: "RENDER_QA",
        status: "COMPLETED",
        started_at: "2026-09-08T17:35:21Z",
        completed_at: "2026-09-08T17:35:25Z",
        output_summary: "Single frame failure at 1042. Memory spike coincides with volumetric VDB explosion cache insertion.",
        findings: [
          {
            id: "fnd-qa-1",
            agent_name: "Render QA",
            finding_type: "ISOLATED_FRAME_FAILURE",
            severity: "HIGH",
            confidence: 0.98,
            title: "Volumetric Memory Spike on Frame 1042",
            description: "Frame 1041 rendered in 3m12s at 28GB peak; frame 1042 triggered instant CUDA abort at 48GB limit.",
          },
        ],
      },
      {
        id: "run-hw-01",
        agent_name: "Hardware Diagnostics Specialist",
        agent_type: "HARDWARE",
        status: "COMPLETED",
        started_at: "2026-09-08T17:35:21Z",
        completed_at: "2026-09-08T17:35:26Z",
        output_summary: "Node blade-42 is healthy (no driver fault, temps within tolerance), but its 48GB VRAM capacity was exhausted.",
        findings: [
          {
            id: "fnd-hw-1",
            agent_name: "Hardware Diagnostics",
            finding_type: "GPU_MEMORY_EXHAUSTION",
            severity: "HIGH",
            confidence: 0.96,
            title: "GPU VRAM Capacity Exhaustion (48GB Pool)",
            description: "Blade-42 has 48GB VRAM. Job requirements peaked above hardware capability; node itself is healthy.",
          },
        ],
      },
      {
        id: "run-hist-01",
        agent_name: "Historical Evidence Specialist",
        agent_type: "HISTORICAL",
        status: "COMPLETED",
        started_at: "2026-09-08T17:35:22Z",
        completed_at: "2026-09-08T17:35:27Z",
        output_summary: "Matched 17 historical incidents with identical CUDA error signature. 14 resolved successfully by retrying on 80GB GPU pool.",
        findings: [
          {
            id: "fnd-hist-1",
            agent_name: "Historical Evidence",
            finding_type: "RESOLVED_PRECEDENT_MATCH",
            severity: "MEDIUM",
            confidence: 0.92,
            title: "82% Precedent Success with 80GB GPU Retry",
            description: "14 of 17 matching historical incidents succeeded when dispatched to H100/A100 80GB nodes.",
          },
        ],
      },
    ],
    reasoning: {
      id: "rsn-01",
      root_cause: "GPU_MEMORY_EXHAUSTION_DURING_VOLUMETRIC_DECOMPRESSION",
      confidence: 0.97,
      severity: "HIGH",
      summary: "Job exceeded the 48GB VRAM barrier of node blade-42 during uncompressed VDB volume loading. Node hardware is fully operational. Routing to 80GB GPU pool will resolve the abort.",
      supporting_evidence: [
        "Arnold telemetry reports 48920MB allocation request on 48GB card",
        "USD stage contains uncompressed 34.2GB VDB fire cache",
        "Historical database records 14 successful precedents resolved via 80GB pool",
      ],
      contradicting_evidence: [
        "No hardware defects or thermal throttling detected on node-blade-42",
      ],
      alternative_causes: [
        { cause: "Shader infinite loop or memory leak", probability: 0.03 },
      ],
      recommended_action: "RETRY_JOB_ON_80GB_NODE",
    },
    remediation_plan: {
      id: "plan-dune-1042",
      strategy: "Reroute job-arnold-8821 to high-capacity 80GB GPU cluster, notify lighting lead, and flag VDB asset for compression.",
      risk_level: "HIGH",
      status: "AWAITING_APPROVAL",
      requires_approval: true,
      rollback_strategy: "Revert priority boost and cancel farm queue ticket if node unavailable.",
      preventive_measures: [
        "Enable NanoVDB level-of-detail compression in Houdini export shelf",
        "Add automated pre-flight memory estimation webhook to Deadline submitter",
      ],
      actions: [
        {
          action: "RETRY_JOB",
          reason: "Resubmit job-arnold-8821 targeting 80GB GPU cluster pool.",
          risk: "HIGH",
          confidence: 0.97,
          requires_human_approval: true,
          parameters: {
            job_id: "job-arnold-8821",
            node_class: "gpu-80gb",
            priority_boost: 15,
            frame_range: "1042-1042",
          },
        },
        {
          action: "UPDATE_SHOT_STATUS",
          reason: "Mark shot status as FARM_RETRYING in ShotGrid.",
          risk: "MEDIUM",
          confidence: 0.95,
          requires_human_approval: true,
          parameters: {
            project: "DUNE_PART_3",
            sequence: "SQ040",
            shot: "SH0120",
            new_status: "review",
            notes: "Retrying frame 1042 on 80GB node pool via automated incident governance.",
          },
        },
        {
          action: "NOTIFY_TEAM",
          reason: "Post incident diagnosis and ETA update to department channel.",
          risk: "LOW",
          confidence: 0.99,
          requires_human_approval: false,
          parameters: {
            channel: "#dune-comp-leads",
            message: "Incident inc-1042-oom: Frame 1042 re-queued on 80GB GPU blade. Expected comp ready at 18:15 UTC.",
            urgency: "high",
          },
        },
      ],
    },
    approvals: [
      {
        id: "appr-dune-001",
        plan_id: "plan-dune-1042",
        action: "RETRY_JOB",
        status: "PENDING",
        risk: "HIGH",
        confidence: 0.97,
        requires_human_approval: true,
        requested_at: "2026-09-08T17:36:00Z",
        parameters: {
          job_id: "job-arnold-8821",
          node_class: "gpu-80gb",
          priority_boost: 15,
          frame_range: "1042-1042",
        },
      },
    ],
    executions: [
      {
        id: "exec-01",
        tool_name: "notify_team",
        status: "SUCCESS",
        actor: "policy_auto_approve",
        parameters: { channel: "#dune-comp-leads", message: "Investigation underway for frame 1042" },
        result: { success: true, message_id: "msg-9921", delivered_at: "2026-09-08T17:35:30Z" },
        executed_at: "2026-09-08T17:35:31Z",
      },
    ],
    precedents: [
      { title: "DUNE_PART_2 SQ012 SH0080 OOM on Sandworm cache", resolution: "Retried on 80GB GPU pool", success_rate: 0.94, similarity: 0.95 },
      { title: "AVATAR_3 SQ090 SH0200 Water splash volume abort", resolution: "Retried on 80GB GPU pool", success_rate: 0.88, similarity: 0.89 },
    ],
  },
  {
    id: "inc-1043-asset",
    correlation_id: "corr-usd-asset-02",
    title: "Missing USD Dependency: texture_bump_v003.exr on Shared SAN",
    description: "Lighting scene load failure: asset validation detected missing texture reference on high-res hero asset.",
    severity: "MEDIUM",
    status: "INVESTIGATING",
    event_type: "ASSET_VALIDATION_FAILED",
    source_system: "asset_storage",
    project: "AVATAR_3",
    sequence: "SQ010",
    shot: "SH0040",
    job_id: "job-maya-5512",
    node_id: "node-blade-18",
    error_signature: "USD_MISSING_TEXTURE_REFERENCE",
    created_at: "2026-09-08T17:15:00Z",
    updated_at: "2026-09-08T17:22:00Z",
    evidence: [],
    agent_runs: [],
    approvals: [],
    executions: [],
  },
  {
    id: "inc-1044-node",
    correlation_id: "corr-node-offline-03",
    title: "Render Node blade-07 Degraded: Thermal Throttle at 93°C",
    description: "GPU driver reporting thermal slowdown; 4 consecutive frame timeouts detected in past 20 minutes.",
    severity: "CRITICAL",
    status: "REMEDIATING",
    event_type: "NODE_UNHEALTHY",
    source_system: "tractor",
    project: "DUNE_PART_3",
    sequence: "SQ020",
    shot: "SH0090",
    node_id: "node-blade-07",
    error_signature: "THERMAL_THROTTLE_GPU_OVERHEAT",
    created_at: "2026-09-08T16:50:00Z",
    updated_at: "2026-09-08T17:10:00Z",
    evidence: [],
    agent_runs: [],
    approvals: [],
    executions: [],
  },
];

export const MOCK_CLUSTER_NODES: ClusterNodeHealth[] = [
  { node_id: "node-blade-01", status: "ONLINE", gpu_utilization: 94, gpu_memory_used_percent: 68, gpu_temperature_celsius: 71, cpu_utilization: 82, scratch_disk_free_gb: 840, active_jobs: 2 },
  { node_id: "node-blade-07", status: "DEGRADED", gpu_utilization: 99, gpu_memory_used_percent: 94, gpu_temperature_celsius: 93, cpu_utilization: 96, scratch_disk_free_gb: 120, active_jobs: 1 },
  { node_id: "node-blade-18", status: "ONLINE", gpu_utilization: 42, gpu_memory_used_percent: 38, gpu_temperature_celsius: 62, cpu_utilization: 35, scratch_disk_free_gb: 1450, active_jobs: 1 },
  { node_id: "node-blade-42", status: "DEGRADED", gpu_utilization: 98, gpu_memory_used_percent: 99, gpu_temperature_celsius: 84, cpu_utilization: 88, scratch_disk_free_gb: 410, active_jobs: 1 },
  { node_id: "node-gpu80-01", status: "ONLINE", gpu_utilization: 78, gpu_memory_used_percent: 52, gpu_temperature_celsius: 67, cpu_utilization: 64, scratch_disk_free_gb: 2800, active_jobs: 3 },
  { node_id: "node-gpu80-02", status: "ONLINE", gpu_utilization: 12, gpu_memory_used_percent: 10, gpu_temperature_celsius: 48, cpu_utilization: 15, scratch_disk_free_gb: 3400, active_jobs: 0 },
];
